https://www.kaggle.com/datasets/jessicali9530/honey-production

About Dataset
Context

In 2006, global concern was raised over the rapid decline in the honeybee population, an integral component to American honey agriculture. Large numbers of hives were lost to Colony Collapse Disorder, a phenomenon of disappearing worker bees causing the remaining hive colony to collapse. Speculation to the cause of this disorder points to hive diseases and pesticides harming the pollinators, though no overall consensus has been reached. Twelve years later, some industries are observing recovery but the American honey industry is still largely struggling. The U.S. used to locally produce over half the honey it consumes per year. Now, honey mostly comes from overseas, with 350 of the 400 million pounds of honey consumed every year originating from imports. This dataset provides insight into honey production supply and demand in America by state from 1998 to 2012.
Content

The National Agricultural Statistics Service (NASS) is the primary data reporting body for the US Department of Agriculture (USDA). NASS's mission is to "provide timely, accurate, and useful statistics in service to U.S. agriculture". From datasets to census surveys, their data covers virtually all aspects of U.S. agriculture. Honey production is one of the datasets offered. Click here for the original page containing the data along with related datasets such as Honey Bee Colonies and Cost of Pollination. Data wrangling was performed in order to clean the dataset. honeyproduction.csv is the final tidy dataset suitable for analysis. The three other datasets (which include "honeyraw" in the title) are the original raw data downloaded from the site. They are uploaded to this page along with the "Wrangling The Honey Production Dataset" kernel as an example to show users how data can be wrangled into a cleaner format. Useful metadata on certain variables of the honeyproduction dataset is provided below:

    numcol: Number of honey producing colonies. Honey producing colonies are the maximum number of colonies from which honey was taken during the year. It is possible to take honey from colonies which did not survive the entire year
    yieldpercol: Honey yield per colony. Unit is pounds
    totalprod: Total production (numcol x yieldpercol). Unit is pounds
    stocks: Refers to stocks held by producers. Unit is pounds
    priceperlb: Refers to average price per pound based on expanded sales. Unit is dollars.
    prodvalue: Value of production (totalprod x priceperlb). Unit is dollars.
    Other useful information: Certain states are excluded every year (ex. CT) to avoid disclosing data for individual operations. Due to rounding, total colonies multiplied by total yield may not equal production. Also, summation of states will not equal U.S. level value of production.

In [2]:
import pandas as pd
df=pd.read_csv('honeyproduction.csv')
print(df.head(5))
print(df.describe())

  state    numcol  yieldpercol   totalprod      stocks  priceperlb  \
0    AL   16000.0           71   1136000.0    159000.0        0.72
1    AZ   55000.0           60   3300000.0   1485000.0        0.64
2    AR   53000.0           65   3445000.0   1688000.0        0.59
3    CA  450000.0           83  37350000.0  12326000.0        0.62
4    CO   27000.0           72   1944000.0   1594000.0        0.70

    prodvalue  year
0    818000.0  1998
1   2112000.0  1998
2   2033000.0  1998
3  23157000.0  1998
4   1361000.0  1998
              numcol  yieldpercol     totalprod        stocks  priceperlb  \
count     626.000000   626.000000  6.260000e+02  6.260000e+02  626.000000
mean    60284.345048    62.009585  4.169086e+06  1.318859e+06    1.409569
std     91077.087231    19.458754  6.883847e+06  2.272964e+06    0.638599
min      2000.000000    19.000000  8.400000e+04  8.000000e+03    0.490000
25%      9000.000000    48.000000  4.750000e+05  1.430000e+05    0.932500
50%     26000.000000    60.000000  1.533000e+06  4.395000e+05    1.360000
75%     63750.000000    74.000000  4.175250e+06  1.489500e+06    1.680000
max    510000.000000   136.000000  4.641000e+07  1.380000e+07    4.150000

          prodvalue         year
count  6.260000e+02   626.000000
mean   4.715741e+06  2004.864217
std    7.976110e+06     4.317306
min    1.620000e+05  1998.000000
25%    7.592500e+05  2001.000000
50%    1.841500e+06  2005.000000
75%    4.703250e+06  2009.000000
max    6.961500e+07  2012.000000

### Reading Data

In [9]:
print(df[['state', 'numcol','yieldpercol', 'totalprod']])

    state    numcol  yieldpercol   totalprod
0      AL   16000.0           71   1136000.0
1      AZ   55000.0           60   3300000.0
2      AR   53000.0           65   3445000.0
3      CA  450000.0           83  37350000.0
4      CO   27000.0           72   1944000.0
..    ...       ...          ...         ...
621    VA    4000.0           41    164000.0
622    WA   62000.0           41   2542000.0
623    WV    6000.0           48    288000.0
624    WI   60000.0           69   4140000.0
625    WY   50000.0           51   2550000.0

[626 rows x 4 columns]

## Sorting/Describing Data

In [10]:
df.sort_values(['state', 'totalprod'], ascending=[1,0])

,state,numcol,yieldpercol,totalprod,stocks,priceperlb,prodvalue,year
86,AL,16000.0,78,1248000.0,187000.0,0.59,736000.0,2000
43,AL,17000.0,68,1156000.0,185000.0,0.56,647000.0,1999
0,AL,16000.0,71,1136000.0,159000.0,0.72,818000.0,1998
217,AL,13000.0,82,1066000.0,43000.0,1.24,1322000.0,2003
261,AL,12000.0,87,1044000.0,282000.0,1.41,1472000.0,2004
...,...,...,...,...,...,...,...,...
465,WY,39000.0,61,2379000.0,381000.0,1.37,3259000.0,2008
342,WY,40000.0,56,2240000.0,291000.0,0.89,1994000.0,2005
585,WY,35000.0,54,1890000.0,265000.0,1.72,3251000.0,2011
505,WY,37000.0,48,1776000.0,391000.0,1.43,2540000.0,2009
545,WY,34000.0,36,1224000.0,282000.0,1.59,1946000.0,2010

## Making changes to the data

In [13]:
#adding stocks value to the table, (stocks X price per lb)
df['stocksval'] = df['stocks'] * df['priceperlb'] 
print(df[['state','stocksval']])

    state  stocksval
0      AL   114480.0
1      AZ   950400.0
2      AR   995920.0
3      CA  7642120.0
4      CO  1115800.0
..    ...        ...
621    VA    86710.0
622    WA  2420460.0
623    WV   276450.0
624    WI  3819150.0
625    WY   858330.0

[626 rows x 2 columns]

In [14]:
df.head()

,state,numcol,yieldpercol,totalprod,stocks,priceperlb,prodvalue,year,stocksval
0,AL,16000.0,71,1136000.0,159000.0,0.72,818000.0,1998,114480.0
1,AZ,55000.0,60,3300000.0,1485000.0,0.64,2112000.0,1998,950400.0
2,AR,53000.0,65,3445000.0,1688000.0,0.59,2033000.0,1998,995920.0
3,CA,450000.0,83,37350000.0,12326000.0,0.62,23157000.0,1998,7642120.0
4,CO,27000.0,72,1944000.0,1594000.0,0.70,1361000.0,1998,1115800.0

## Saving our Data (Exporting into Desired Format)

In [15]:
df.to_csv('modifiedhoneyprod.csv', index=False)
df.to_csv('modifiedhoneyprod.txt', index=False, sep='\t')

## Filtering Data

In [16]:
newdf= df.loc[(df['state']== 'AL')]#honey production from alabama only
newdf

,state,numcol,yieldpercol,totalprod,stocks,priceperlb,prodvalue,year,stocksval
0,AL,16000.0,71,1136000.0,159000.0,0.72,818000.0,1998,114480.0
43,AL,17000.0,68,1156000.0,185000.0,0.56,647000.0,1999,103600.0
86,AL,16000.0,78,1248000.0,187000.0,0.59,736000.0,2000,110330.0
129,AL,14000.0,73,1022000.0,235000.0,0.72,736000.0,2001,169200.0
173,AL,12000.0,86,1032000.0,103000.0,1.18,1218000.0,2002,121540.0
217,AL,13000.0,82,1066000.0,43000.0,1.24,1322000.0,2003,53320.0
261,AL,12000.0,87,1044000.0,282000.0,1.41,1472000.0,2004,397620.0
302,AL,13000.0,66,858000.0,266000.0,1.02,875000.0,2005,271320.0
343,AL,11000.0,72,792000.0,230000.0,1.21,958000.0,2006,278300.0
384,AL,11000.0,56,616000.0,209000.0,1.49,918000.0,2007,311410.0
425,AL,9000.0,66,594000.0,214000.0,1.90,1129000.0,2008,406600.0
466,AL,9000.0,50,450000.0,68000.0,1.86,837000.0,2009,126480.0
506,AL,9000.0,54,486000.0,73000.0,2.40,1166000.0,2010,175200.0
546,AL,9000.0,50,450000.0,63000.0,2.51,1130000.0,2011,158130.0
586,AL,8000.0,54,432000.0,65000.0,2.47,1067000.0,2012,160550.0

In [20]:
df.loc[(df['numcol'] > 9000) & (df['totalprod']>450000)]#filtering the df with parameter : numcol = 9000 and tatalprod : 450000

,state,numcol,yieldpercol,totalprod,stocks,priceperlb,prodvalue,year,stocksval
0,AL,16000.0,71,1136000.0,159000.0,0.72,818000.0,1998,114480.0
1,AZ,55000.0,60,3300000.0,1485000.0,0.64,2112000.0,1998,950400.0
2,AR,53000.0,65,3445000.0,1688000.0,0.59,2033000.0,1998,995920.0
3,CA,450000.0,83,37350000.0,12326000.0,0.62,23157000.0,1998,7642120.0
4,CO,27000.0,72,1944000.0,1594000.0,0.70,1361000.0,1998,1115800.0
...,...,...,...,...,...,...,...,...,...
618,TX,92000.0,52,4784000.0,718000.0,2.00,9568000.0,2012,1436000.0
619,UT,25000.0,38,950000.0,209000.0,1.87,1777000.0,2012,390830.0
622,WA,62000.0,41,2542000.0,1017000.0,2.38,6050000.0,2012,2420460.0
624,WI,60000.0,69,4140000.0,1863000.0,2.05,8487000.0,2012,3819150.0
625,WY,50000.0,51,2550000.0,459000.0,1.87,4769000.0,2012,858330.0

## conditional changes

In [29]:
df.loc[df['state'] == 'AL', 'state'] = 'ALA'#changing the state from AL to ALA
df

,state,numcol,yieldpercol,totalprod,stocks,priceperlb,prodvalue,year,stocksval
0,ALA,16000.0,71,1136000.0,159000.0,0.72,818000.0,1998,114480.0
1,AZ,55000.0,60,3300000.0,1485000.0,0.64,2112000.0,1998,950400.0
2,AR,53000.0,65,3445000.0,1688000.0,0.59,2033000.0,1998,995920.0
3,CA,450000.0,83,37350000.0,12326000.0,0.62,23157000.0,1998,7642120.0
4,CO,27000.0,72,1944000.0,1594000.0,0.70,1361000.0,1998,1115800.0
...,...,...,...,...,...,...,...,...,...
621,VA,4000.0,41,164000.0,23000.0,3.77,618000.0,2012,86710.0
622,WA,62000.0,41,2542000.0,1017000.0,2.38,6050000.0,2012,2420460.0
623,WV,6000.0,48,288000.0,95000.0,2.91,838000.0,2012,276450.0
624,WI,60000.0,69,4140000.0,1863000.0,2.05,8487000.0,2012,3819150.0
625,WY,50000.0,51,2550000.0,459000.0,1.87,4769000.0,2012,858330.0

## Aggregate Statistics (groupby)

In [4]:
#grouping the dataframe by something
df_state_mean = df.groupby(['state']).mean()
df_state_mean.to_csv('df_state_mean.csv')
df_year_mean = df.groupby(['year']).mean()
df_year_mean.to_csv('df_year_mean.csv')
df_state_sum = df.groupby(['state']).sum()
df_state_sum.to_csv('df_state_sum.csv')
df_year_sum = df.groupby(['year']).sum()
df_year_mean.to_csv('df_year_sum.csv')
print(df_state_mean)
print(df_year_mean)

              numcol  yieldpercol     totalprod        stocks  priceperlb  \
state
AL      11933.333333    67.533333  8.254667e+05  1.588000e+05    1.418667
AR      36800.000000    73.933333  2.810400e+06  9.926667e+05    1.092000
AZ      33666.666667    60.066667  2.032267e+06  8.770000e+05    1.134667
CA     406666.666667    55.800000  2.316900e+07  6.453800e+06    1.133333
CO      28000.000000    62.800000  1.750600e+06  8.152667e+05    1.229333
FL     195200.000000    83.066667  1.646987e+07  2.209600e+06    1.100667
GA      60400.000000    54.666667  3.299933e+06  3.522667e+05    1.185333
HI       8733.333333    98.000000  8.431333e+05  1.702000e+05    1.710000
IA      31466.666667    65.733333  2.080000e+06  1.129933e+06    1.320667
ID      99400.000000    44.000000  4.410667e+06  1.875933e+06    1.138000
IL       8066.666667    61.666667  4.983333e+05  2.099333e+05    2.139333
IN       7933.333333    60.933333  4.840000e+05  2.026000e+05    1.526000
KS      12600.000000    56.066667  7.079333e+05  3.492000e+05    1.412667
KY       4400.000000    52.133333  2.296667e+05  4.693333e+04    2.082667
LA      37666.666667    95.733333  3.627333e+06  5.437333e+05    1.054000
MD       4666.666667    45.000000  2.110000e+05  4.850000e+04    1.561667
ME       8400.000000    31.066667  2.467333e+05  9.633333e+04    1.432000
MI      71133.333333    68.133333  4.854667e+06  2.295600e+06    1.232000
MN     128933.333333    74.266667  9.624000e+06  2.185800e+06    1.152000
MO      15666.666667    53.400000  8.715333e+05  2.032667e+05    1.378000
MS      16800.000000    87.466667  1.456867e+06  3.145333e+05    1.058667
MT     136000.000000    77.333333  1.043747e+07  3.196667e+06    1.150667
NC      11400.000000    47.800000  5.427333e+05  1.265333e+05    2.074000
ND     370333.333333    88.066667  3.167233e+07  8.859867e+06    1.125333
NE      46333.333333    67.466667  3.158600e+06  1.689333e+06    1.172667
NJ      10933.333333    36.933333  3.995333e+05  1.148000e+05    1.509333
NM       8733.333333    53.866667  4.764667e+05  2.349333e+05    1.318000
NV       9818.181818    45.181818  4.392727e+05  1.464545e+05    2.219091
NY      56400.000000    69.133333  3.937467e+06  1.774467e+06    1.361333
OH      16133.333333    63.533333  1.040067e+06  4.333333e+05    1.590667
OK       4500.000000    46.333333  2.011667e+05  6.683333e+04    1.456667
OR      48600.000000    44.400000  2.121400e+06  1.078867e+06    1.252667
PA      25733.333333    50.400000  1.295600e+06  5.552000e+05    1.521333
SC       5333.333333    68.000000  3.433333e+05  2.966667e+04    1.310000
SD     236266.666667    75.800000  1.774273e+07  8.766267e+06    1.140000
TN       7200.000000    56.333333  4.077333e+05  9.786667e+04    1.894000
TX      98533.333333    70.533333  6.993600e+06  1.368000e+06    1.114667
UT      25333.333333    46.533333  1.179067e+06  3.076667e+05    1.166667
VA       6600.000000    40.200000  2.665333e+05  6.693333e+04    2.320000
VT       5666.666667    66.933333  3.880667e+05  1.522667e+05    1.585333
WA      55666.666667    48.800000  2.687733e+06  1.110200e+06    1.248000
WI      68133.333333    79.400000  5.455533e+06  2.848400e+06    1.272000
WV       6533.333333    48.533333  3.212000e+05  1.337333e+05    1.834667
WY      39533.333333    66.133333  2.617933e+06  4.822000e+05    1.148000

          prodvalue    year
state
AL     1.001933e+06  2005.0
AR     2.684400e+06  2005.0
AZ     2.111800e+06  2005.0
CA     2.435933e+07  2005.0
CO     2.090267e+06  2005.0
FL     1.661527e+07  2005.0
GA     3.867533e+06  2005.0
HI     1.404200e+06  2005.0
IA     2.588333e+06  2005.0
ID     4.762067e+06  2005.0
IL     1.007533e+06  2005.0
IN     6.905333e+05  2005.0
KS     9.240667e+05  2005.0
KY     4.799333e+05  2005.0
LA     3.620200e+06  2005.0
MD     3.055000e+05  2000.5
ME     3.378000e+05  2005.0
MI     5.786933e+06  2005.0
MN     1.052333e+07  2005.0
MO     9.845333e+05  2005.0
MS     1.616800e+06  2005.0
MT     1.179353e+07  2005.0
NC     1.143867e+06  2005.0
ND     3.637613e+07  2005.0
NE     3.526333e+06  2005.0
NJ     6.070000e+05  2005.0
NM     5.472000e+05  2005.0
NV     9.699091e+05  2003.0
NY     5.004200e+06  2005.0
OH     1.552133e+06  2005.0
OK     2.851667e+05  2000.5
OR     2.623267e+06  2005.0
PA     1.849667e+06  2005.0
SC     4.460000e+05  2002.0
SD     1.937673e+07  2005.0
TN     7.599333e+05  2005.0
TX     7.429200e+06  2005.0
UT     1.344333e+06  2005.0
VA     5.722000e+05  2005.0
VT     5.623333e+05  2005.0
WA     3.319133e+06  2005.0
WI     6.513733e+06  2005.0
WV     5.526000e+05  2005.0
WY     2.856533e+06  2005.0
            numcol  yieldpercol     totalprod        stocks  priceperlb  \
year
1998  60953.488372    69.953488  5.105093e+06  1.873605e+06    0.832558
1999  61325.581395    65.465116  4.706674e+06  1.823023e+06    0.804186
2000  60558.139535    67.581395  5.106000e+06  1.975721e+06    0.791395
2001  57772.727273    64.545455  4.221545e+06  1.471909e+06    0.911818
2002  58295.454545    66.795455  3.892386e+06  8.903864e+05    1.371364
2003  58886.363636    62.545455  4.122091e+06  9.231591e+05    1.494773
2004  61926.829268    64.804878  4.456805e+06  1.487341e+06    1.284634
2005  58390.243902    64.268293  4.243146e+06  1.516756e+06    1.195122
2006  58000.000000    61.853659  3.761902e+06  1.469146e+06    1.303659
2007  59219.512195    59.170732  3.600512e+06  1.278171e+06    1.438293
2008  56731.707317    61.000000  3.974927e+06  1.243805e+06    1.625610
2009  61800.000000    53.850000  3.626700e+06  9.330500e+05    1.812000
2010  66650.000000    56.275000  4.382350e+06  1.119925e+06    1.929000
2011  61650.000000    54.775000  3.680025e+06  9.137500e+05    2.167250
2012  62725.000000    55.175000  3.522675e+06  7.915500e+05    2.367000

         prodvalue
year
1998  3.397465e+06
1999  2.875744e+06
2000  3.059721e+06
2001  3.006409e+06
2002  5.165955e+06
2003  5.729068e+06
2004  4.812366e+06
2005  3.921780e+06
2006  3.851805e+06
2007  3.935512e+06
2008  5.609561e+06
2009  5.348000e+06
2010  6.959250e+06
2011  6.467200e+06
2012  7.018125e+06

## working with large amount of data

In [36]:
for df in pd.read_csv('honeyproduction.csv', chunksize=10):
    print('chunk DF')
    print(df)

chunk DF
  state  numcol  yieldpercol   totalprod    stocks  priceperlb  prodvalue  \
0    AL   16000           71   1136000.0    159000        0.72     818000
1    AZ   55000           60   3300000.0   1485000        0.64    2112000
2    AR   53000           65   3445000.0   1688000        0.59    2033000
3    CA  450000           83  37350000.0  12326000        0.62   23157000
4    CO   27000           72   1944000.0   1594000        0.70    1361000
5    FL  230000           98  22540000.0   4508000        0.64   14426000
6    GA   75000           56   4200000.0    307000        0.69    2898000
7    HI    8000          118    944000.0     66000        0.77     727000
8    ID  120000           50   6000000.0   2220000        0.65    3900000
9    IL    9000           71    639000.0    204000        1.19     760000

   year
0  1998
1  1998
2  1998
3  1998
4  1998
5  1998
6  1998
7  1998
8  1998
9  1998
chunk DF
   state  numcol  yieldpercol  totalprod   stocks  priceperlb  prodvalue  year
10    IN    9000           92     828000   489000        0.85     704000  1998
11    IA   50000           78    3900000  2301000        0.70    2730000  1998
12    KS   16000           46     736000   390000        0.87     640000  1998
13    KY    3000           50     150000    51000        1.40     210000  1998
14    LA   41000          111    4551000   865000        0.59    2685000  1998
15    ME   10000           26     260000   117000        0.69     179000  1998
16    MD    7000           44     308000    92000        1.10     339000  1998
17    MI   80000           85    6800000  3672000        0.66    4488000  1998
18    MN  140000           79   11060000  2765000        0.65    7189000  1998
19    MS   18000           86    1548000   898000        0.58     898000  1998
chunk DF
   state  numcol  yieldpercol  totalprod   stocks  priceperlb  prodvalue  year
20    MO   23000           66    1518000   455000        0.76    1154000  1998
21    MT  115000          122   14030000  5472000        0.64    8979000  1998
22    NE   64000           70    4480000  2240000        0.86    3853000  1998
23    NV   10000           46     460000   175000        1.65     759000  1998
24    NJ   11000           49     539000   167000        0.76     410000  1998
25    NM   14000           55     770000   470000        0.76     585000  1998
26    NY   65000           80    5200000  2444000        0.70    3640000  1998
27    NC    8000           59     472000   151000        1.38     651000  1998
28    ND  230000          128   29440000  8832000        0.63   18547000  1998
29    OH   18000           78    1404000   702000        0.83    1165000  1998
chunk DF
   state  numcol  yieldpercol  totalprod    stocks  priceperlb  prodvalue  \
30    OK    4000           51     204000     63000        1.24     253000
31    OR   50000           45    2250000   1620000        0.90    2025000
32    PA   26000           66    1716000    789000        0.80    1373000
33    SD  225000           95   21375000  10901000        0.64   13680000
34    TN    7000           64     448000    121000        1.32     591000
35    TX   91000           77    7007000   1612000        0.62    4344000
36    UT   30000           58    1740000    557000        0.65    1131000
37    VT    6000           64     384000    207000        0.85     326000
38    VA    8000           37     296000     86000        1.33     394000
39    WA   58000           51    2958000   1361000        0.64    1893000

    year
30  1998
31  1998
32  1998
33  1998
34  1998
35  1998
36  1998
37  1998
38  1998
39  1998
chunk DF
   state  numcol  yieldpercol  totalprod   stocks  priceperlb  prodvalue  year
40    WV    6000           55     330000   155000        1.14     376000  1998
41    WI   89000           91    8099000  5264000        0.72    5831000  1998
42    WY   46000           60    2760000   524000        0.68    1877000  1998
43    AL   17000           68    1156000   185000        0.56     647000  1999
44    AZ   52000           62    3224000  1548000        0.62    1999000  1999
45    AR   52000           89    4628000  2592000        0.53    2453000  1999
46    CA  465000           60   27900000  9486000        0.55   15345000  1999
47    CO   27000           76    2052000  1436000        0.68    1395000  1999
48    FL  228000          102   23256000  4186000        0.53   12326000  1999
49    GA   65000           51    3315000   497000        0.64    2122000  1999
chunk DF
   state  numcol  yieldpercol  totalprod   stocks  priceperlb  prodvalue  year
50    HI    8000           80     640000    32000        0.80     512000  1999
51    ID  120000           48    5760000  3110000        0.59    3398000  1999
52    IL    9000           66     594000   327000        1.15     683000  1999
53    IN   10000           81     810000   437000        0.90     729000  1999
54    IA   40000           65    2600000  2028000        0.65    1690000  1999
55    KS   13000           67     871000   854000        1.11     967000  1999
56    KY    3000           50     150000    12000        1.24     186000  1999
57    LA   48000          114    5472000   821000        0.49    2681000  1999
58    ME   14000           22     308000    89000        0.83     256000  1999
59    MD    6000           46     276000    50000        1.64     453000  1999
chunk DF
   state  numcol  yieldpercol  totalprod   stocks  priceperlb  prodvalue  year
60    MI   73000           85    6205000  3475000        0.66    4095000  1999
61    MN  145000           82   11890000  3210000        0.61    7253000  1999
62    MS   18000           73    1314000   591000        0.54     710000  1999
63    MO   24000           65    1560000   437000        0.68    1061000  1999
64    MT  122000           70    8540000  2135000        0.60    5124000  1999
65    NE   58000           77    4466000  1965000        0.61    2724000  1999
66    NV    9000           45     405000   271000        1.54     624000  1999
67    NJ   10000           44     440000   154000        0.57     251000  1999
68    NM   15000           52     780000   476000        0.77     601000  1999
69    NY   69000           70    4830000  2077000        0.66    3188000  1999
chunk DF
   state  numcol  yieldpercol  totalprod    stocks  priceperlb  prodvalue  \
70    NC    9000           46     414000    104000        1.62     671000
71    ND  255000          105   26775000   8836000        0.59   15797000
72    OH   20000           74    1480000    784000        0.72    1066000
73    OK    6000           45     270000     49000        1.34     362000
74    OR   45000           57    2565000   2026000        0.80    2052000
75    PA   28000           60    1680000    790000        0.76    1277000
76    SD  224000          104   23296000  13046000        0.60   13978000
77    TN    8000           51     408000    106000        1.30     530000
78    TX  108000           81    8748000   2799000        0.64    5599000
79    UT   26000           45    1170000    433000        0.68     796000

    year
70  1999
71  1999
72  1999
73  1999
74  1999
75  1999
76  1999
77  1999
78  1999
79  1999
chunk DF
   state  numcol  yieldpercol   totalprod    stocks  priceperlb  prodvalue  \
80    VT    6000           66    396000.0    222000        0.63     249000
81    VA    7000           35    245000.0     86000        1.17     287000
82    WA   52000           50   2600000.0   1170000        0.60    1560000
83    WV    6000           39    234000.0    152000        1.09     255000
84    WI   80000           75   6000000.0   4560000        0.68    4080000
85    WY   37000           72   2664000.0    746000        0.61    1625000
86    AL   16000           78   1248000.0    187000        0.59     736000
87    AZ   40000           59   2360000.0   1322000        0.73    1723000
88    AR   52000           93   4836000.0   3337000        0.57    2757000
89    CA  440000           70  30800000.0  11396000        0.59   18172000

    year
80  1999
81  1999
82  1999
83  1999
84  1999
85  1999
86  2000
87  2000
88  2000
89  2000
chunk DF
   state    numcol  yieldpercol  totalprod   stocks  priceperlb  prodvalue  \
90    CO   29000.0           60    1740000   957000        0.62    1079000
91    FL  232000.0          105   24360000  2923000        0.54   13154000
92    GA   55000.0           57    3135000   376000        0.63    1975000
93    HI    7000.0          112     784000   125000        0.82     643000
94    ID  100000.0           47    4700000  2679000        0.52    2444000
95    IL    8000.0           61     488000   146000        1.17     571000
96    IN    8000.0           65     520000   286000        1.03     536000
97    IA   30000.0           67    2010000  1206000        0.68    1367000
98    KS   15000.0           68    1020000   520000        0.91     928000
99    KY    4000.0           48     192000    54000        1.35     259000

    year
90  2000
91  2000
92  2000
93  2000
94  2000
95  2000
96  2000
97  2000
98  2000
99  2000
chunk DF
    state  numcol  yieldpercol  totalprod   stocks  priceperlb  prodvalue  \
100    LA   43000           94    4042000  1334000        0.52    2102000
101    ME   11000           21     231000   143000        0.75     173000
102    MD    6000           46     276000    52000        1.14     315000
103    MI   72000           75    5400000  2970000        0.60    3240000
104    MN  150000           90   13500000  3105000        0.57    7695000
105    MS   17000           72    1224000   649000        0.69     845000
106    MO   23000           75    1725000   362000        0.60    1035000
107    MT  124000           88   10912000  4692000        0.59    6438000
108    NE   50000           87    4350000  2610000        0.59    2567000
109    NV   10000           35     350000    95000        1.45     508000

     year
100  2000
101  2000
102  2000
103  2000
104  2000
105  2000
106  2000
107  2000
108  2000
109  2000
chunk DF
    state    numcol  yieldpercol  totalprod      stocks  priceperlb  \
110    NJ   11000.0           35     385000    200000.0        0.61
111    NM   15000.0           64     960000    739000.0        0.72
112    NY   58000.0           80    4640000   2274000.0        0.55
113    NC   11000.0           49     539000    243000.0        1.43
114    ND  300000.0          115   34500000  13800000.0        0.57
115    OH   18000.0           65    1170000    585000.0        0.79
116    OK    7000.0           35     245000     64000.0        1.26
117    OR   48000.0           51    2448000   1665000.0        0.66
118    PA   25000.0           45    1125000    630000.0        0.76
119    SD  235000.0          121   28435000  12796000.0        0.58

     prodvalue  year
110     235000  2000
111     691000  2000
112    2552000  2000
113     771000  2000
114   19665000  2000
115     924000  2000
116     309000  2000
117    1616000  2000
118     855000  2000
119   16492000  2000
chunk DF
    state  numcol  yieldpercol  totalprod   stocks  priceperlb  prodvalue  \
120    TN    9000           61     549000   104000        1.43     785000
121    TX  105000           79    8295000  2986000        0.57    4728000
122    UT   24000           41     984000   462000        0.60     590000
123    VT    7000           59     413000   211000        0.68     281000
124    VA    7000           42     294000   103000        1.50     441000
125    WA   52000           54    2808000  1151000        0.58    1629000
126    WV    7000           54     378000   234000        1.22     461000
127    WI   84000           90    7560000  4385000        0.68    5141000
128    WY   39000           93    3627000   798000        0.59    2140000
129    AL   14000           73    1022000   235000        0.72     736000

     year
120  2000
121  2000
122  2000
123  2000
124  2000
125  2000
126  2000
127  2000
128  2000
129  2001
chunk DF
    state    numcol  yieldpercol   totalprod   stocks  priceperlb  prodvalue  \
130    AZ   43000.0           59   2537000.0  1142000        0.72    1827000
131    AR   50000.0           98   4900000.0  1617000        0.65    3185000
132    CA  460000.0           61  28060000.0  7857000        0.69   19361000
133    CO   26000.0           55   1430000.0   529000        0.71    1015000
134    FL  220000.0          100  22000000.0  3432000        0.64   14080000
135    GA   55000.0           57   3135000.0   188000        0.70    2195000
136    HI    8000.0           87    696000.0    84000        0.87     606000
137    ID  100000.0           46   4600000.0  1610000        0.67    3082000
138    IL    6000.0           76    456000.0   251000        1.58     720000
139    IN    7000.0           76    532000.0   186000        0.92     489000

     year
130  2001
131  2001
132  2001
133  2001
134  2001
135  2001
136  2001
137  2001
138  2001
139  2001
chunk DF
    state  numcol  yieldpercol  totalprod   stocks  priceperlb  prodvalue  \
140    IA   33000           51    1683000   875000        0.75    1262000
141    KS   13000           51     663000   530000        0.96     636000
142    KY    4000           78     312000   125000        1.41     440000
143    LA   45000          106    4770000   572000        0.60    2862000
144    ME   11000           20     220000   106000        0.79     174000
145    MD    4000           46     184000    55000        1.60     294000
146    MI   76000           60    4560000  2827000        0.81    3694000
147    MN  135000           81   10935000  1859000        0.65    7108000
148    MS   17000           66    1122000   224000        0.89     999000
149    MO   22000           61    1342000   336000        0.71     953000

     year
140  2001
141  2001
142  2001
143  2001
144  2001
145  2001
146  2001
147  2001
148  2001
149  2001
chunk DF
    state  numcol  yieldpercol   totalprod   stocks  priceperlb  prodvalue  \
150    MT  136000          102  13872000.0  4578000        0.67    9294000
151    NE   43000           48   2064000.0  1115000        0.72    1486000
152    NV    9000           50    450000.0    36000        2.14     963000
153    NJ   11000           34    374000.0    71000        0.85     318000
154    NM   10000           70    700000.0   350000        0.66     462000
155    NY   53000           70   3710000.0  1781000        0.79    2931000
156    NC   13000           44    572000.0   172000        1.48     847000
157    ND  280000           96  26880000.0  9408000        0.69   18547000
158    OH   18000           81   1458000.0   569000        1.01    1473000
159    OK    4000           47    188000.0   105000        1.43     269000

     year
150  2001
151  2001
152  2001
153  2001
154  2001
155  2001
156  2001
157  2001
158  2001
159  2001
chunk DF
    state  numcol  yieldpercol  totalprod    stocks  priceperlb  prodvalue  \
160    OR   44000           44    1936000   1200000        0.74    1433000
161    PA   26000           57    1482000    785000        0.92    1363000
162    SC    7000           40     280000     67000        0.79     221000
163    SD  235000           65   15275000  12220000        0.71   10845000
164    TN    8000           59     472000    131000        1.39     656000
165    TX   97000           79    7663000   1533000        0.65    4981000
166    UT   23000           38     874000    315000        0.65     568000
167    VT    7000           81     567000    249000        0.92     522000
168    VA    9000           52     468000     94000        1.26     590000
169    WA   48000           52    2496000   1048000        0.72    1797000

     year
160  2001
161  2001
162  2001
163  2001
164  2001
165  2001
166  2001
167  2001
168  2001
169  2001
chunk DF
    state  numcol  yieldpercol  totalprod   stocks  priceperlb  prodvalue  \
170    WV    7000           65     455000   410000        1.42     646000
171    WI   67000           81    5427000  3419000        0.82    4450000
172    WY   38000           77    2926000   468000        0.65    1902000
173    AL   12000           86    1032000   103000        1.18    1218000
174    AZ   38000           63    2394000  1197000        1.08    2586000
175    AR   45000           88    3960000   871000        1.26    4990000
176    CA  470000           50   23500000  3525000        1.32   31020000
177    CO   24000           60    1440000   576000        1.29    1858000
178    FL  220000           93   20460000  2026000        1.14   23324000
179    GA   50000           52    2600000    52000        1.13    2938000

     year
170  2001
171  2001
172  2001
173  2002
174  2002
175  2002
176  2002
177  2002
178  2002
179  2002
chunk DF
    state    numcol  yieldpercol  totalprod   stocks  priceperlb  prodvalue  \
180    HI    7000.0          136     952000    29000        1.11    1057000
181    ID  100000.0           57    5700000  1653000        1.37    7809000
182    IL    9000.0           80     720000   130000        1.47    1058000
183    IN    8000.0           62     496000   233000        1.19     590000
184    IA   33000.0           70    2310000   901000        1.43    3303000
185    KS   17000.0           52     884000   407000        1.50    1326000
186    KY    5000.0           54     270000    78000        1.63     440000
187    LA   35000.0          124    4340000   347000        1.16    5034000
188    ME   11000.0           41     451000   266000        1.21     546000
189    MD    3000.0           46     138000    21000        1.96     270000

     year
180  2002
181  2002
182  2002
183  2002
184  2002
185  2002
186  2002
187  2002
188  2002
189  2002
chunk DF
    state  numcol  yieldpercol  totalprod   stocks  priceperlb  prodvalue  \
190    MI   72000           77  5544000.0  1885000        1.40    7762000
191    MN  117000           73  8541000.0  1110000        1.47   12555000
192    MS   18000           78  1404000.0   281000        1.23    1727000
193    MO   18000           50   900000.0   189000        1.42    1278000
194    MT  134000           63  8442000.0  1097000        1.38   11650000
195    NE   43000           75  3225000.0  1161000        1.49    4805000
196    NV    9000           62   558000.0    61000        2.67    1490000
197    NJ   11000           40   440000.0    92000        1.00     440000
198    NM   11000           44   484000.0   252000        1.10     532000
199    NY   60000           98  5880000.0  2470000        1.25    7350000

     year
190  2002
191  2002
192  2002
193  2002
194  2002
195  2002
196  2002
197  2002
198  2002
199  2002
chunk DF
    state  numcol  yieldpercol   totalprod   stocks  priceperlb  prodvalue  \
200    NC   16000           42    672000.0    74000        1.41     948000
201    ND  320000           75  24000000.0  8160000        1.46   35040000
202    OH   18000           70   1260000.0   504000        1.44    1814000
203    OK    3000           53    159000.0    51000        1.63     259000
204    OR   43000           49   2107000.0   885000        1.35    2844000
205    PA   29000           57   1653000.0   827000        1.34    2215000
206    SC    5000           94    470000.0    14000        1.25     588000
207    SD  225000           51  11475000.0  2410000        1.42   16295000
208    TN    8000           61    488000.0   137000        1.40     683000
209    TX  114000           67   7638000.0   985000        1.14    8707000

     year
200  2002
201  2002
202  2002
203  2002
204  2002
205  2002
206  2002
207  2002
208  2002
209  2002
chunk DF
    state  numcol  yieldpercol  totalprod   stocks  priceperlb  prodvalue  \
210    UT   22000           59  1298000.0   208000        1.30    1687000
211    VT    7000           89   623000.0   274000        1.20     748000
212    VA    8000           38   304000.0    79000        1.90     578000
213    WA   50000           51  2550000.0   561000        1.27    3239000
214    WV    9000           51   459000.0   151000        1.32     606000